---
name: Codestyle checks

'on':
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  shellcheck:
    name: Run shellcheck style checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2

      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Prefetch shell.nix
        run: 'nix-shell --run true'

      - run: nix-shell --run "make shellcheck"

  yamllint:
    name: Run yamllint on github actions files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2

      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Prefetch shell.nix
        run: 'nix-shell --run true'

      - run: nix-shell --run "make yamllint"
