---
name: Codestyle checks

'on':
  pull_request:
    branches:
      - main

  push:
    branches:
      - main
      - nodejs-frontend  # TODO: Remove me when web-frontend is merged

jobs:
  yamllint:
    name: Run yamllint on github actions files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Prefetch shell.nix
        run: 'nix-shell --run true'

      - run: nix-shell --run "make yamllint"
